import { alpha, Colors, type AppColorTheme } from '@/constants/theme';
import { StyleSheet } from 'react-native';

type StyleFactory = (colors: AppColorTheme, compact: boolean, isDark: boolean) => Record<string, any>;

const baseStyles: StyleFactory = (colors, compact, isDark) => ({
  root: {
    flex: 1,
    backgroundColor: colors.shellBackground,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.shellBackground,
  },
  content: {
    paddingTop: 28,
    paddingHorizontal: compact ? 16 : 18,
    paddingBottom: 164,
    gap: 20,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  brandBlock: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center', gap: 12,
  },
  brandAvatar: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.shellCardMuted,
  },
  brandName: {
    flex: 1,
    minWidth: 0,
    color: colors.primary,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  brandGreeting: {
    color: colors.shellTextMuted,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  iconButton: {
    position: 'relative',
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.shellCard,
    borderWidth: 1,
    borderColor: colors.shellBorder,
  },
  notificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.danger,
    borderWidth: 2,
    borderColor: colors.shellBackground,
  },
  notificationBadgeText: {
    color: colors.onPrimary,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '900',
  },
  loadingState: {
    marginTop: 20,
    borderRadius: 24,
    backgroundColor: colors.shellCardSoft,
    paddingVertical: 40,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: colors.shellBorder,
  },
  loadingText: {
    color: colors.shellTextSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  heroBlock: {
    gap: 12,
    borderRadius: 24,
    backgroundColor: colors.shellCard,
    padding: compact ? 18 : 20,
    borderWidth: 1,
    borderColor: colors.shellBorder,
  },
  filterCard: {
    borderRadius: 20,
    backgroundColor: colors.shellCardSoft,
    padding: compact ? 14 : 16,
    borderWidth: 1,
    borderColor: colors.shellBorder,
  },
  filterCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  filterCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  filterCardKicker: {
    color: colors.shellTextSoft,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  filterCardTitle: {
    color: colors.shellTextPrimary,
    fontSize: compact ? 18 : 20,
    lineHeight: compact ? 24 : 26,
    fontWeight: '800',
    letterSpacing: -0.7,
  },
  filterCardMeta: {
    color: colors.shellTextMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  filterCardAction: {
    flexShrink: 0,
    minHeight: 40,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
  },
  filterCardActionText: {
    color: colors.onPrimary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  kicker: {
    color: colors.secondary,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 3.2,
  },
  heroAmount: {
    color: colors.shellTextPrimary,
    fontSize: compact ? 44 : 56,
    lineHeight: compact ? 48 : 62,
    fontWeight: '900',
    letterSpacing: -2.4,
  },
  momentumRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
  },
  momentumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 16,
    backgroundColor: alpha(colors.secondary, isDark ? 0.28 : 0.12),
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  momentumBadgeText: {
    color: colors.secondary,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  momentumHint: {
    flexShrink: 1,
    color: colors.shellTextMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  card: {
    borderRadius: 22,
    backgroundColor: colors.shellCard,
    padding: compact ? 17 : 19,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.shellBorder,
  },
  showMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: alpha(colors.primary, isDark ? 0.1 : 0.06),
    borderWidth: 1,
    borderColor: alpha(colors.primary, isDark ? 0.18 : 0.1),
  },
  showMoreButtonText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  summaryCard: {
    borderRadius: 22,
    backgroundColor: colors.shellCard,
    padding: compact ? 18 : 20,
    gap: 14,
    borderWidth: 1,
    borderColor: alpha(colors.primary, isDark ? 0.16 : 0.1),
  },
  liquidCard: {
    borderRadius: 22,
    backgroundColor: colors.shellCardMuted,
    padding: compact ? 18 : 20,
    gap: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.shellBorder,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
  },
  sectionTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  cardEyebrow: {
    color: colors.shellTextSoft,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  liquidAmount: {
    color: colors.shellTextPrimary,
    fontSize: compact ? 18 : 20,
    lineHeight: compact ? 22 : 24,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  cardIconShell: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDark ? alpha(colors.secondary, 0.22) : colors.warningSoft,
    borderWidth: 1,
    borderColor: isDark ? alpha(colors.secondary, 0.18) : alpha(colors.warning, 0.2),
    shadowColor: isDark ? colors.background : colors.warningSoft,
    shadowOpacity: isDark ? 0 : 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  progressTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: colors.shellCardMuted,
    overflow: 'hidden',
  },
  progressFillPrimary: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: colors.primary,
  },
  liquidMetaRow: {
    flexDirection: compact ? 'column' : 'row',
    alignItems: compact ? 'flex-start' : 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  cardMeta: {
    flex: 1,
    width: compact ? '100%' : undefined,
    color: colors.shellTextSoft,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
  },
  cardTitle: {
    flex: 1,
    minWidth: 0,
    color: colors.shellTextPrimary,
    fontSize: compact ? 23 : 25,
    lineHeight: compact ? 30 : 32,
    fontWeight: '800',
    letterSpacing: -1.1,
  },
  cardHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  summaryBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: alpha(colors.shellTextPrimary, isDark ? 0.12 : 0.08),
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  summaryBadgeDanger: {
    backgroundColor: alpha(colors.danger, isDark ? 0.18 : 0.12),
  },
  summaryBadgeLabel: {
    color: colors.shellTextPrimary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  summaryBadgeLabelDanger: {
    color: colors.danger,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  summaryMetric: {
    width: compact ? '100%' : '48%',
    borderRadius: 16,
    backgroundColor: colors.shellCardSoft,
    padding: 13,
    gap: 6,
    borderWidth: 1,
    borderColor: colors.shellBorder,
  },
  summaryMetricLabel: {
    color: colors.shellTextSoft,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    lineHeight: 14,
  },
  summaryMetricValue: {
    color: colors.shellTextPrimary,
    fontSize: compact ? 18 : 20,
    lineHeight: compact ? 24 : 26,
    fontWeight: '900',
    letterSpacing: -0.7,
    width: '100%',
    flexShrink: 1,
    textAlign: 'left',
    includeFontPadding: false,
  },
  summaryMetricMeta: {
    color: colors.shellTextMuted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    flexShrink: 1,
  },
  summaryStatsRow: {
    flexDirection: compact ? 'column' : 'row',
    gap: 12,
  },
  summaryStatPill: {
    flex: 1,
    width: compact ? '100%' : undefined,
    borderRadius: 16,
    backgroundColor: colors.shellCardSoft,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 3,
    alignItems: 'flex-start',
  },
  summaryStatLabel: {
    color: colors.shellTextSoft,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  summaryStatValue: {
    color: colors.shellTextPrimary,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  filterBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  filterBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: alpha(colors.primary, isDark ? 0.12 : 0.08),
    borderWidth: 1,
    borderColor: alpha(colors.primary, isDark ? 0.24 : 0.16),
  },
  filterBadgeText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
  },
  errorText: {
    color: colors.danger,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '700',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  linkText: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  cardDescription: {
    color: colors.shellTextMuted,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
  },
  secondaryAction: {
    minHeight: 54,
    borderRadius: 20,
    backgroundColor: colors.shellTextPrimary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
  },
  secondaryActionText: {
    color: colors.onPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  primaryAction: {
    alignSelf: 'flex-start',
    minHeight: 56,
    borderRadius: 20,
    backgroundColor: colors.onPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    marginTop: 4,
  },
  primaryActionText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
});

export const createBaseStyles = (colors: AppColorTheme, width: number, topInset: number, bottomInset: number) => {
  const compact = width < 360;
  const isDark = colors.background === Colors.dark.background;
  const raw = baseStyles(colors, compact, isDark);

  return StyleSheet.create({
    ...raw,
    content: {
      ...raw.content,
      paddingTop: Math.max(topInset + 14, 28),
    },
    fabContainer: {
      position: 'absolute',
      bottom: Math.max(bottomInset + 90, 100),
      right: 18,
      zIndex: 100,
      alignItems: 'flex-end',
      gap: 12,
    },
  });
};
