import { alpha, type AppColorTheme } from '@/constants/theme';
import { type ViewStyle, type TextStyle, type ImageStyle } from 'react-native';

type AnyStyle = ViewStyle | TextStyle | ImageStyle;

export const componentStyles = (colors: AppColorTheme, compact: boolean, isDark: boolean): Record<string, AnyStyle> => ({
  segmentedControl: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0, backgroundColor: colors.shellCardSoft, borderRadius: 16, padding: 4 },
  segmentButton: { minWidth: compact ? 56 : 64, alignItems: 'center', justifyContent: 'center', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 8 },
  segmentButtonMuted: { backgroundColor: alpha(colors.shellTextPrimary, isDark ? 0.08 : 0.06) },
  segmentButtonActive: { backgroundColor: colors.primary },
  segmentLabel: { fontSize: 10, fontWeight: '800', color: colors.shellTextMuted },
  segmentLabelActive: { color: colors.shellTextPrimary },
  segmentLabelSelected: { color: colors.onPrimary },
  trendChart: { height: compact ? 180 : 208, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: compact ? 8 : 10, paddingTop: 8 },
  trendItem: { flex: 1, minWidth: 0, height: '100%', alignItems: 'center', justifyContent: 'flex-end', gap: 12, position: 'relative' },
  trendBar: { width: '100%', minHeight: 34, borderTopLeftRadius: 10, borderTopRightRadius: 10, backgroundColor: colors.shellCardMuted },
  trendBarActive: { backgroundColor: colors.primary, shadowColor: alpha(colors.primary, 0.2), shadowOpacity: 1, shadowRadius: 8, shadowOffset: { width: 0, height: 2 } },
  trendLabel: { color: colors.shellTextMuted, fontSize: 10, fontWeight: '800', letterSpacing: 1.4 },
  trendEmpty: { flex: 1, minHeight: 160, alignItems: 'center', justifyContent: 'center', gap: 8, paddingHorizontal: 20 },
  trendEmptyTitle: { color: colors.shellTextPrimary, fontSize: 14, fontWeight: '800', textAlign: 'center' },
  trendEmptyMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  tooltipContainer: { position: 'absolute', top: -36, left: '50%', transform: [{ translateX: -40 }], backgroundColor: colors.shellTextPrimary, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, alignItems: 'center' },
  tooltipText: { color: colors.onPrimary, fontSize: 11, fontWeight: '700' },
  tooltipArrow: { position: 'absolute', bottom: -5, left: '50%', transform: [{ translateX: -3 }], width: 0, height: 0, borderLeftWidth: 6, borderRightWidth: 6, borderTopWidth: 6, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderTopColor: colors.shellTextPrimary },
  debtStatusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  debtStatusPill: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  debtStatusPillText: { fontSize: 10, lineHeight: 12, fontWeight: '900', letterSpacing: 1, textTransform: 'uppercase' },
  debtStatusMeta: { flex: 1, minWidth: 0, color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '700', textAlign: 'right' },
  debtStatusTrack: { height: 4, borderRadius: 999, backgroundColor: colors.shellCardSoft, overflow: 'hidden', marginTop: 2 },
  debtStatusFill: { height: '100%', borderRadius: 999 },
  metricCard: { borderRadius: 16, backgroundColor: colors.shellCardSoft, paddingHorizontal: 16, paddingVertical: 14, gap: 4 },
  metricValue: { color: colors.shellTextPrimary, fontSize: 18, fontWeight: '900', letterSpacing: -0.6 },
  metricMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '600' },
  activityList: { gap: 12 },
  activityItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  activityLeft: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 12 },
  activityIconWrap: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardSoft },
  activityCopy: { flex: 1, minWidth: 0, gap: 3 },
  activityTitle: { color: colors.shellTextPrimary, fontSize: 14, lineHeight: 18, fontWeight: '800' },
  activityMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '500' },
  activityRight: { width: compact ? 84 : 96, alignItems: 'flex-end', gap: 3 },
  activityAmount: { color: colors.shellTextPrimary, fontSize: compact ? 14 : 16, lineHeight: compact ? 18 : 20, fontWeight: '900', letterSpacing: -0.6 },
  activityAmountPositive: { color: colors.secondary },
  activityKind: { color: colors.shellTextSoft, fontSize: 9, fontWeight: '700' },
  merchantItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: alpha(colors.surfaceContainerHighest, 0.2) },
  merchantLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  merchantRank: { width: 28, height: 28, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.primary, 0.1) },
  merchantRankText: { color: colors.primary, fontSize: 12, fontWeight: '800' },
  merchantName: { color: colors.shellTextPrimary, fontSize: 14, fontWeight: '700' },
  merchantMeta: { color: colors.shellTextMuted, fontSize: 11, fontWeight: '500' },
  merchantRight: { alignItems: 'flex-end' },
  merchantAmount: { color: colors.shellTextPrimary, fontSize: 14, fontWeight: '800' },
  billsRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: alpha(colors.surfaceContainerHighest, 0.2) },
  billsIconWrap: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.danger, 0.1) },
  billsCopy: { flex: 1, gap: 2 },
  billsTitle: { color: colors.shellTextPrimary, fontSize: 14, fontWeight: '700' },
  billsMeta: { color: colors.shellTextMuted, fontSize: 12, fontWeight: '500' },
  billsRight: { alignItems: 'flex-end' },
  billsAmount: { color: colors.danger, fontSize: 14, fontWeight: '800' },
  walletItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: alpha(colors.surfaceContainerHighest, 0.2) },
  walletLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  walletIconWrap: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.primary, 0.1) },
  walletName: { color: colors.shellTextPrimary, fontSize: 14, fontWeight: '700' },
  walletBalance: { color: colors.shellTextPrimary, fontSize: 14, fontWeight: '800' },
});
