import { alpha, type AppColorTheme } from '@/constants/theme';
import { type ViewStyle, type TextStyle, type ImageStyle } from 'react-native';

type AnyStyle = ViewStyle | TextStyle | ImageStyle;

export const insightStyles = (colors: AppColorTheme, compact: boolean, isDark: boolean): Record<string, AnyStyle> => ({
  insightCard: { borderRadius: 22, backgroundColor: colors.shellCardStrong, padding: compact ? 18 : 20, gap: 16, overflow: 'hidden', shadowColor: alpha(colors.shellTextPrimary, 0.08), shadowOpacity: 1, shadowRadius: 10, shadowOffset: { width: 0, height: 8 }, borderWidth: 1, borderColor: colors.shellBorder },
  insightBadge: { alignSelf: 'flex-start', borderRadius: 8, backgroundColor: colors.shellCardSoft, paddingHorizontal: 10, paddingVertical: 6, color: colors.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' },
  insightHero: { flexDirection: 'column', alignItems: 'flex-start', gap: 12 },
  insightHeroTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, flex: 1, minWidth: 0 },
  insightHeroBadge: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardSoft, flexShrink: 0 },
  insightHeroCopy: { flex: 1, minWidth: 0, gap: 6 },
  insightHeroPill: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start', borderRadius: 999, backgroundColor: colors.shellCardSoft, paddingHorizontal: 10, paddingVertical: 6, flexShrink: 0, marginTop: 4 },
  insightHeroPillText: { color: colors.shellTextPrimary, fontSize: 10, lineHeight: 12, fontWeight: '800', letterSpacing: 0.8, textTransform: 'uppercase' },
  insightTitle: { color: colors.shellTextPrimary, fontSize: compact ? 22 : 24, lineHeight: compact ? 30 : 32, fontWeight: '800', letterSpacing: -1 },
  insightText: { color: colors.shellTextMuted, fontSize: 14, lineHeight: 20, fontWeight: '500' },
  insightSignalGrid: { flexDirection: compact ? 'column' : 'row', gap: 12 },
  insightSignalCard: { flex: 1, borderRadius: 20, backgroundColor: colors.shellCard, padding: 14, gap: 5, borderWidth: 1, borderColor: colors.shellBorder, minHeight: 108 },
  insightSignalIcon: { width: 32, height: 32, borderRadius: 999, alignItems: 'center', justifyContent: 'center', marginBottom: 2 },
  insightSignalLabel: { color: colors.shellTextSoft, fontSize: 10, lineHeight: 12, fontWeight: '800', letterSpacing: 1, textTransform: 'uppercase' },
  insightSignalValue: { color: colors.shellTextPrimary, fontSize: 17, lineHeight: 22, fontWeight: '900', letterSpacing: -0.4 },
  insightSignalMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '600' },
  insightCompareStrip: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20, backgroundColor: colors.shellCard, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderColor: colors.shellBorder },
  insightCompareIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardSoft, flexShrink: 0 },
  insightCompareCopy: { flex: 1, minWidth: 0, gap: 2 },
  insightCompareTitle: { color: colors.shellTextPrimary, fontSize: 13, lineHeight: 18, fontWeight: '800', letterSpacing: -0.2 },
  insightCompareMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '500' },
  insightCompareChips: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0 },
  insightCompareChip: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5 },
  insightCompareChipText: { fontSize: 10, lineHeight: 12, fontWeight: '900', letterSpacing: 0.5 },
  insightCategorySection: { gap: 12, borderRadius: 20, backgroundColor: colors.shellCard, padding: 12, borderWidth: 1, borderColor: colors.shellBorder },
  insightSectionHeader: { gap: 2 },
  insightSectionTitle: { color: colors.shellTextPrimary, fontSize: 13, lineHeight: 18, fontWeight: '800', letterSpacing: -0.2 },
  insightSectionMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '500' },
  insightStackBar: { flexDirection: 'row', height: 8, borderRadius: 999, backgroundColor: colors.shellCardSoft, overflow: 'hidden', gap: 2 },
  insightStackSegment: { height: '100%', borderRadius: 999 },
  insightCategoryList: { gap: 8 },
  insightCategoryItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  insightCategoryIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  insightCategoryCopy: { flex: 1, minWidth: 0, gap: 2 },
  insightCategoryTitle: { color: colors.shellTextPrimary, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  insightCategoryMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 14, fontWeight: '500' },
  insightCategoryRight: { width: 108, alignItems: 'flex-end', gap: 4 },
  insightCategoryPercent: { color: colors.onPrimary, fontSize: 12, lineHeight: 13, fontWeight: '800', letterSpacing: 0.6 },
  insightCategoryBarTrack: { width: '100%', height: 4, borderRadius: 999, backgroundColor: colors.shellCardSoft, overflow: 'hidden' },
  insightCategoryBarFill: { height: '100%', borderRadius: 999 },
  insightList: { gap: 12 },
  insightItem: { flexDirection: 'row', gap: 12, alignItems: 'flex-start', paddingVertical: 8, borderTopWidth: 1, borderTopColor: alpha(colors.onPrimary, 0.12) },
  insightItemRail: { width: 3, alignSelf: 'stretch', borderRadius: 999, marginTop: 3, opacity: 0.75 },
  insightItemCopy: { flex: 1, gap: 4 },
  insightItemHead: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  insightItemTag: { alignSelf: 'flex-start', borderRadius: 999, backgroundColor: colors.shellCardSoft, paddingHorizontal: 8, paddingVertical: 4, fontSize: 9, lineHeight: 11, fontWeight: '900', letterSpacing: 0.8, textTransform: 'uppercase' },
  insightItemIcon: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardSoft, marginTop: 2, flexShrink: 0 },
  insightItemTitle: { color: colors.shellTextPrimary, fontSize: 15, lineHeight: 21, fontWeight: '800', letterSpacing: -0.2 },
  insightItemText: { color: colors.shellTextMuted, fontSize: 13, lineHeight: 19, fontWeight: '500' },
  insightEmptyText: { color: colors.shellTextMuted, fontSize: 14, lineHeight: 20, fontWeight: '500' },
});
