import { alpha, type AppColorTheme } from '@/constants/theme';
import { type ViewStyle, type TextStyle, type ImageStyle } from 'react-native';

type AnyStyle = ViewStyle | TextStyle | ImageStyle;

export const modalStyles = (colors: AppColorTheme, compact: boolean, isDark: boolean): Record<string, AnyStyle> => ({
  filterModalOverlay: { flex: 1 },
  filterModalBackdrop: { flex: 1, justifyContent: 'flex-end' },
  filterModalSheet: { maxHeight: '90%', borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: colors.shellBackground, borderWidth: 1, borderColor: colors.shellBorder, overflow: 'hidden' },
  filterModalHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 999, marginTop: 10, marginBottom: 12, backgroundColor: colors.shellCardMuted },
  filterModalBody: { gap: 16, paddingHorizontal: compact ? 16 : 18, paddingBottom: 16 },
  filterModalHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  filterModalHeaderCopy: { flex: 1, minWidth: 0, gap: 4 },
  filterModalKicker: { color: colors.secondary, fontSize: 10, fontWeight: '800', letterSpacing: 2, textTransform: 'uppercase' },
  filterModalTitle: { color: colors.shellTextPrimary, fontSize: compact ? 22 : 24, lineHeight: compact ? 28 : 30, fontWeight: '900', letterSpacing: -0.9 },
  filterModalSubtitle: { color: colors.shellTextMuted, fontSize: 13, lineHeight: 20, fontWeight: '500' },
  filterModalClose: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder },
  filterModalScroll: { maxHeight: compact ? 360 : 420 },
  filterModalContent: { gap: 14, paddingBottom: 4 },
  filterSectionCard: { borderRadius: 22, backgroundColor: colors.shellCard, padding: compact ? 16 : 18, gap: 16, borderWidth: 1, borderColor: colors.shellBorder },
  filterSectionHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  filterSectionIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.primary, 0.12) },
  filterSectionCopy: { flex: 1, minWidth: 0, gap: 2 },
  filterSectionTitle: { color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '800' },
  filterSectionSubtitle: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 18, fontWeight: '500' },
  filterModeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  filterModeButton: { flexGrow: 1, flexBasis: '48%', minHeight: 52, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: colors.shellCardMuted, borderWidth: 1, borderColor: colors.shellBorder },
  filterModeIcon: { width: 30, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  filterModeLabel: { color: colors.shellTextMuted, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 },
  filterCycleInfo: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: alpha(colors.primary, isDark ? 0.08 : 0.05), borderRadius: 16, padding: 14, borderWidth: 1, borderColor: alpha(colors.primary, isDark ? 0.2 : 0.12) },
  filterCycleText: { color: colors.shellTextPrimary, fontSize: 12, lineHeight: 18, fontWeight: '600' },
  filterCycleMeta: { color: colors.shellTextMuted, fontSize: 11, lineHeight: 16, fontWeight: '500', marginTop: 2 },
  filterCycleAction: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.primary, 0.12) },
  filterFieldGroup: { gap: 8 },
  filterYearRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  filterYearButton: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardMuted, borderWidth: 1, borderColor: colors.shellBorder },
  filterYearText: { flex: 1, textAlign: 'center', color: colors.shellTextPrimary, fontSize: 20, lineHeight: 26, fontWeight: '900', letterSpacing: -0.7 },
  filterMonthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  filterMonthChip: { flexGrow: 1, flexBasis: '20%', minHeight: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardMuted, borderWidth: 1, borderColor: colors.shellBorder },
  filterMonthChipText: { color: colors.shellTextSecondary, fontSize: 12, fontWeight: '700' },
  filterFieldLabel: { color: colors.shellTextPrimary, fontSize: 12, fontWeight: '800', letterSpacing: 0.5, textTransform: 'uppercase' },
  filterPickerShell: { minHeight: 56, borderRadius: 16, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: colors.shellCardMuted, borderWidth: 1, borderColor: colors.shellBorder, flexDirection: 'row', alignItems: 'center', gap: 12 },
  filterPickerPressed: { opacity: 0.88, transform: [{ scale: 0.995 }] },
  filterPickerIcon: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.primary, 0.12), flexShrink: 0 },
  filterPickerCopy: { flex: 1, minWidth: 0, gap: 2 },
  filterPickerValue: { color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '800', letterSpacing: -0.2 },
  filterPickerMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '500' },
  iosDatePickerOverlay: { position: 'absolute', inset: 0, justifyContent: 'flex-end', zIndex: 100 },
  iosDatePickerSheet: { backgroundColor: colors.shellCard, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 20, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 20, shadowOffset: { width: 0, height: -4 }, elevation: 10 },
  iosDatePickerDone: { alignItems: 'center', paddingVertical: 12, marginHorizontal: 16, borderRadius: 12, backgroundColor: colors.primary },
  iosDatePickerDoneText: { color: colors.onPrimary, fontSize: 15, fontWeight: '800' },
  filterErrorCard: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, borderRadius: 16, backgroundColor: alpha(colors.danger, isDark ? 0.16 : 0.08), padding: 14, borderWidth: 1, borderColor: alpha(colors.danger, isDark ? 0.32 : 0.2) },
  filterErrorText: { flex: 1, minWidth: 0, color: colors.danger, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  filterModalFooter: { borderTopWidth: 1, borderTopColor: colors.shellBorder, paddingHorizontal: compact ? 16 : 18, paddingTop: 14, paddingBottom: 16, backgroundColor: colors.shellBackground },
  filterModalActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  filterSecondaryButton: { flex: 1, minHeight: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardMuted, borderWidth: 1, borderColor: colors.shellBorder },
  filterSecondaryButtonText: { color: colors.shellTextPrimary, fontSize: 13, fontWeight: '800' },
  filterPrimaryButton: { flex: 1, minHeight: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary },
  filterPrimaryButtonText: { color: colors.onPrimary, fontSize: 13, fontWeight: '800' },
  monthPickerOverlay: { flex: 1, justifyContent: 'center', paddingHorizontal: compact ? 16 : 20, backgroundColor: alpha(colors.inverseSurface, isDark ? 0.7 : 0.36) },
  monthPickerSheet: { borderRadius: 28, backgroundColor: colors.shellBackground, borderWidth: 1, borderColor: colors.shellBorder, padding: compact ? 16 : 18, gap: 16, overflow: 'hidden' },
  monthPickerHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 999, backgroundColor: colors.shellCardMuted },
  monthPickerHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  monthPickerHeaderCopy: { flex: 1, minWidth: 0, gap: 4 },
  monthPickerKicker: { color: colors.secondary, fontSize: 10, fontWeight: '800', letterSpacing: 2, textTransform: 'uppercase' },
  monthPickerTitle: { color: colors.shellTextPrimary, fontSize: compact ? 21 : 23, lineHeight: compact ? 27 : 29, fontWeight: '900', letterSpacing: -0.9 },
  monthPickerSubtitle: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 18, fontWeight: '500' },
  monthPickerClose: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder },
  monthPickerYearRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, borderRadius: 20, backgroundColor: colors.shellCardMuted, padding: 10 },
  monthPickerYearButton: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder },
  monthPickerYearText: { color: colors.shellTextPrimary, fontSize: 18, lineHeight: 22, fontWeight: '900', letterSpacing: -0.6 },
  monthPickerGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  monthPickerChip: { width: '31%', minHeight: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardMuted, borderWidth: 1, borderColor: colors.shellBorder },
  monthPickerChipText: { color: colors.shellTextSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 0.4, textTransform: 'uppercase' },
  monthPickerActions: { flexDirection: 'row', gap: 12 },
  monthPickerSecondaryButton: { flex: 1, minHeight: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCardMuted, borderWidth: 1, borderColor: colors.shellBorder },
  monthPickerSecondaryButtonText: { color: colors.shellTextPrimary, fontSize: 13, fontWeight: '800' },
  monthPickerPrimaryButton: { flex: 1, minHeight: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary },
  monthPickerPrimaryButtonText: { color: colors.onPrimary, fontSize: 13, fontWeight: '800' },
  debtPayOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.25)', justifyContent: 'flex-end' },
  debtPaySheet: { margin: 16, borderRadius: 16, backgroundColor: colors.shellCard, padding: 16, borderWidth: 1, borderColor: colors.shellBorder },
  debtPayHandle: { width: 40, height: 4, borderRadius: 4, backgroundColor: colors.shellBorder, alignSelf: 'center', marginBottom: 12 },
  debtPayHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  debtPayTitle: { fontSize: 16, fontWeight: '800', color: colors.shellTextPrimary },
  debtPayBody: { marginTop: 4, marginBottom: 12 },
  debtPayLabel: { color: colors.shellTextMuted, fontSize: 12, fontWeight: '700', marginBottom: 6 },
  debtPayInput: { height: 44, borderRadius: 10, borderWidth: 1, borderColor: colors.shellBorder, paddingHorizontal: 12, backgroundColor: colors.shellCardSoft, color: colors.shellTextPrimary },
  debtPayActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12, alignItems: 'center' },
  debtPayCancel: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 10, backgroundColor: colors.shellCardSoft },
  debtPayCancelText: { color: colors.shellTextPrimary, fontWeight: '800' },
  debtPayPay: { paddingVertical: 10, paddingHorizontal: 16, borderRadius: 10, backgroundColor: colors.primary },
  debtPayPayText: { color: colors.onPrimary, fontWeight: '800' },
});
