import { alpha, type AppColorTheme } from '@/constants/theme';
import { StyleSheet } from 'react-native';

const DAY_SUMMARY_STYLES = (colors: AppColorTheme) =>
  StyleSheet.create({
    card: { borderRadius: 18, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, paddingHorizontal: 14, paddingVertical: 12 },
    row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    label: { flexShrink: 1, color: colors.shellTextMuted, fontSize: 11, lineHeight: 16, fontWeight: '800', letterSpacing: 0.8, textTransform: 'uppercase' },
    value: { flexShrink: 0, fontSize: 14, lineHeight: 18, fontWeight: '900', letterSpacing: -0.2, includeFontPadding: false, textAlign: 'right' },
    divider: { height: 1, backgroundColor: alpha(colors.surfaceContainerHighest, 0.2), marginVertical: 10 },
  });

const ROW_STYLES = (colors: AppColorTheme) =>
  StyleSheet.create({
    card: { borderRadius: 24, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, paddingHorizontal: 18, paddingVertical: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    pressed: { opacity: 0.94 },
    left: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 14 },
    iconWrap: { width: 48, height: 48, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    copy: { flex: 1, minWidth: 0, gap: 3 },
    title: { color: colors.shellTextPrimary, fontSize: 16, lineHeight: 22, fontWeight: '800' },
    subtitle: { color: colors.shellTextMuted, fontSize: 13, lineHeight: 18, fontWeight: '500' },
    right: { width: 108, alignItems: 'flex-end', gap: 8 },
    amount: { color: colors.shellTextPrimary, fontSize: 16, lineHeight: 20, fontWeight: '900', letterSpacing: -0.5 },
    statusChip: { minHeight: 26, borderRadius: 999, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
    statusText: { fontSize: 10, lineHeight: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  });

export const createStyles = (colors: AppColorTheme, topInset: number, bottomInset: number) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.shellBackground },
    content: { paddingHorizontal: 18, paddingTop: Math.max(topInset + 12, 26), paddingBottom: Math.max(bottomInset + 126, 150), gap: 18 },
    hero: { gap: 8, paddingTop: 10 },
    titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    kicker: { color: colors.primaryContainer, fontSize: 12, lineHeight: 16, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 2.6 },
    title: { color: colors.shellTextPrimary, fontSize: 34, lineHeight: 40, fontWeight: '900', letterSpacing: -1.2, flex: 1, minWidth: 0 },
    inlineCreateButton: { width: 40, height: 40, borderRadius: 14, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
    toolbarRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'nowrap', marginBottom: 12, position: 'relative', zIndex: 2 },
    searchShell: { flex: 1, minWidth: 0, flexShrink: 1, minHeight: 56, borderRadius: 18, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', gap: 10, marginRight: 12, overflow: 'hidden', position: 'relative', zIndex: 2, elevation: 2 },
    searchShellFocused: { borderColor: alpha(colors.primary, 0.28), shadowColor: colors.primary, shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 1 },
    searchInput: { flex: 1, minWidth: 0, color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '500', paddingVertical: 0 },
    searchClearButton: { width: 30, height: 30, borderRadius: 999, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.surfaceContainerHighest, 0.6) },
    collapsedSection: { height: 0, marginTop: 0, marginBottom: 0, paddingTop: 0, paddingBottom: 0, overflow: 'hidden' },
    filterCardButton: { width: 56, height: 56, borderRadius: 18, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, alignItems: 'center', justifyContent: 'center', position: 'relative', flexShrink: 0, zIndex: 1 },
    filterLauncherBadge: { position: 'absolute', top: 6, right: 6, minWidth: 18, height: 18, borderRadius: 999, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
    filterLauncherBadgeText: { color: colors.onPrimary, fontSize: 10, lineHeight: 12, fontWeight: '900' },
    filterSummaryCard: { borderRadius: 24, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, padding: 16, gap: 12, position: 'relative', zIndex: 1 },
    filterSummaryHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    filterSummaryCopy: { flex: 1, minWidth: 0, gap: 2 },
    filterSummaryKicker: { color: colors.primary, fontSize: 10, lineHeight: 13, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.6 },
    filterSummaryTitle: { color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '800' },
    filterSummaryText: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '500' },
    filterSummaryAction: { flexShrink: 0, minHeight: 36, borderRadius: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: colors.primary },
    filterSummaryActionText: { color: colors.onPrimary, fontSize: 11, fontWeight: '800', letterSpacing: 0.2 },
    filterChipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    monthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    filterChip: { minHeight: 30, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: alpha(colors.primary, 0.1), borderWidth: 1, borderColor: alpha(colors.primary, 0.2), alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 5 },
    filterChipActive: { backgroundColor: alpha(colors.primary, 0.12), borderColor: alpha(colors.primary, 0.28) },
    filterChipText: { color: colors.primary, fontSize: 11, lineHeight: 14, fontWeight: '700' },
    filterChipTextActive: { color: colors.primary },
    filterChipBalance: { color: colors.shellTextSecondary, fontSize: 9, lineHeight: 12, fontWeight: '600', marginTop: 2 },
    filterChipBalanceActive: { color: alpha(colors.primary, 0.7) },
    monthChip: { minWidth: '22%' as any },
    monthSummaryCard: { borderRadius: 18, backgroundColor: colors.shellCardSoft, borderWidth: 1, borderColor: colors.shellBorder, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
    monthSummaryIcon: { width: 38, height: 38, borderRadius: 14, backgroundColor: alpha(colors.primary, 0.12), alignItems: 'center', justifyContent: 'center' },
    monthSummaryCopy: { flex: 1, minWidth: 0, gap: 2 },
    monthSummaryTitle: { color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '800' },
    monthSummaryMeta: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 17, fontWeight: '600' },
    summaryStack: { gap: 14, marginTop: 6 },
    stateCard: { borderRadius: 26, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, padding: 24, gap: 12, alignItems: 'center', justifyContent: 'center' },
    stateText: { color: colors.shellTextSecondary, fontSize: 14, lineHeight: 20, fontWeight: '600', textAlign: 'center' as const },
    emptyTitle: { color: colors.shellTextPrimary, fontSize: 18, lineHeight: 24, fontWeight: '800', textAlign: 'center' as const },
    emptyBody: { color: colors.shellTextMuted, fontSize: 14, lineHeight: 22, fontWeight: '500', textAlign: 'center' as const },
    groupSection: { gap: 14, marginTop: 8 },
    groupHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    groupSummaryRow: { marginTop: -2 },
    groupTitle: { color: colors.shellTextSoft, fontSize: 12, lineHeight: 16, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 2.4 },
    groupLine: { flex: 1, height: 1, backgroundColor: alpha(colors.surfaceContainerHighest, 0.24) },
    groupList: { gap: 12 },
    loadMoreButton: { minHeight: 50, borderRadius: 18, borderWidth: 1, borderColor: colors.shellBorder, backgroundColor: colors.shellCard, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
    loadMoreText: { color: colors.primary, fontSize: 14, fontWeight: '800' },
    errorText: { color: colors.danger, fontSize: 13, lineHeight: 20, fontWeight: '700' },
    modalOverlay: { flex: 1 },
    modalBackdrop: { flex: 1, backgroundColor: alpha(colors.inverseSurface, 0.36), justifyContent: 'flex-end' as const },
    modalKeyboard: { flex: 1, justifyContent: 'flex-end' as const },
    modalSheet: { maxHeight: '92%', borderTopLeftRadius: 32, borderTopRightRadius: 32, backgroundColor: colors.shellBackground, paddingHorizontal: 18, paddingTop: 10, paddingBottom: 0, gap: 16, borderTopWidth: 1, borderColor: colors.shellBorder },
    modalSheetKeyboard: { paddingBottom: Math.max(bottomInset + 20, 24) },
    modalHandle: { alignSelf: 'center' as const, width: 46, height: 5, borderRadius: 999, backgroundColor: alpha(colors.shellTextSoft, 0.5), marginBottom: 2 },
    modalHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' as const, gap: 12 },
    modalHeaderCopy: { flex: 1, minWidth: 0, gap: 4 },
    modalBody: { gap: 16, flexShrink: 1, minHeight: 0 },
    modalKicker: { fontSize: 11, lineHeight: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.8 },
    modalTitle: { color: colors.shellTextPrimary, fontSize: 22, lineHeight: 28, fontWeight: '900', letterSpacing: -0.8 },
    modalSubtitle: { color: colors.shellTextMuted, fontSize: 13, lineHeight: 18, fontWeight: '500', marginTop: 2 },
    closeButton: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder },
    modalScroll: { flexGrow: 0 },
    modalLoadingState: { paddingVertical: 36, alignItems: 'center', justifyContent: 'center', gap: 12 },
    formContent: { gap: 14, paddingBottom: 18 },
    modalHeroCard: { borderRadius: 28, borderWidth: 1, padding: 18, gap: 16 },
    modalHeroMain: { flexDirection: 'row', alignItems: 'center', gap: 14 },
    modalHeroIcon: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    modalHeroCopy: { flex: 1, minWidth: 0, gap: 3 },
    modalHeroTitle: { color: colors.shellTextPrimary, fontSize: 18, lineHeight: 22, fontWeight: '900' },
    modalHeroText: { color: colors.shellTextSecondary, fontSize: 13, lineHeight: 18, fontWeight: '600' },
    modalHeroMetrics: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 12 },
    modalMetric: { flex: 1, minWidth: 0, gap: 4 },
    modalMetricLabel: { color: colors.shellTextMuted, fontSize: 11, lineHeight: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.4 },
    modalMetricValue: { color: colors.shellTextPrimary, fontSize: 20, lineHeight: 24, fontWeight: '900', letterSpacing: -0.6 },
    modalMetricValueMuted: { color: colors.shellTextMuted },
    modalMetricBadge: { minHeight: 34, maxWidth: '48%' as any, borderRadius: 14, borderWidth: 1, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
    modalMetricBadgeText: { fontSize: 11, lineHeight: 14, fontWeight: '800' },
    modalSectionCard: { borderRadius: 26, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, padding: 16, gap: 14 },
    modalSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    modalSectionIcon: { width: 38, height: 38, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
    modalSectionCopy: { flex: 1, minWidth: 0, gap: 2 },
    modalSectionTitle: { color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '800' },
    modalSectionSubtitle: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 17, fontWeight: '600' },
    typeSegment: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    typePill: { flexGrow: 1, flexBasis: '45%' as any, minHeight: 52, borderRadius: 18, backgroundColor: colors.shellCardSoft, borderWidth: 1, borderColor: colors.shellBorder, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
    typePillIcon: { width: 30, height: 30, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
    typePillText: { color: colors.shellTextSecondary, fontSize: 11, lineHeight: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5 },
    cycleInfoCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: alpha(colors.primary, 0.06), borderRadius: 16, padding: 14, borderWidth: 1, borderColor: alpha(colors.primary, 0.14) },
    cycleInfoText: { color: colors.shellTextPrimary, fontSize: 12, lineHeight: 18, fontWeight: '600' },
    cycleInfoMeta: { color: colors.shellTextMuted, fontSize: 11, lineHeight: 16, fontWeight: '500', marginTop: 2 },
    cycleEditButton: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: alpha(colors.primary, 0.12) },
    fieldGroup: { gap: 8 },
    fieldGrid: { flexDirection: 'row', gap: 12 },
    fieldHalf: { flex: 1, minWidth: 0 },
    fieldLabel: { color: colors.shellTextPrimary, fontSize: 13, lineHeight: 16, fontWeight: '700' },
    inputShell: { minHeight: 56, borderRadius: 18, backgroundColor: colors.shellCardSoft, borderWidth: 1, borderColor: colors.shellBorder, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
    inputIconWrap: { width: 34, height: 34, borderRadius: 12, backgroundColor: colors.shellCardMuted, alignItems: 'center', justifyContent: 'center', marginLeft: 2, marginTop: 2 },
    inputControl: { flex: 1, minWidth: 0, color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '600', paddingVertical: 16, paddingRight: 14 },
    inputDisplayText: { flex: 1, minWidth: 0, color: colors.shellTextPrimary, fontSize: 15, lineHeight: 20, fontWeight: '600', paddingVertical: 16, paddingRight: 14 },
    datePickerCard: { borderRadius: 18, backgroundColor: colors.shellCardSoft, borderWidth: 1, borderColor: colors.shellBorder, paddingHorizontal: 6, paddingVertical: 4 },
    iosDatePickerOverlay: { position: 'absolute' as const, inset: 0, justifyContent: 'flex-end' as const, zIndex: 200 },
    iosDatePickerSheet: { backgroundColor: colors.shellCard, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 20, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 20, shadowOffset: { width: 0, height: -4 }, elevation: 10 },
    iosDatePickerDone: { alignItems: 'center' as const, paddingVertical: 12, marginHorizontal: 16, borderRadius: 12, backgroundColor: colors.primary },
    iosDatePickerDoneText: { color: colors.onPrimary, fontSize: 15, fontWeight: '800', overflow: 'hidden' as const },
    textareaShell: { minHeight: 132, alignItems: 'flex-start' as const, paddingTop: 10 },
    textareaInput: { minHeight: 104, paddingTop: 8 },
    categoryWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    categoryChip: { minHeight: 38, borderRadius: 14, paddingHorizontal: 14, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
    categoryChipActive: { backgroundColor: alpha(colors.primary, 0.12), borderColor: alpha(colors.primary, 0.32) },
    categoryChipText: { color: colors.shellTextSecondary, fontSize: 13, lineHeight: 16, fontWeight: '700' },
    categoryChipTextActive: { color: colors.primary },
    emptyCategoryBox: { borderRadius: 18, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, padding: 14, gap: 10 },
    emptyCategoryText: { color: colors.shellTextMuted, fontSize: 13, lineHeight: 18, fontWeight: '500' },
    emptyCategoryButton: { alignSelf: 'flex-start' as const, minHeight: 34, borderRadius: 12, backgroundColor: colors.primary, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
    emptyCategoryButtonText: { color: colors.onPrimary, fontSize: 12, fontWeight: '800' },
    formErrorCard: { borderRadius: 18, backgroundColor: alpha(colors.danger, 0.08), borderWidth: 1, borderColor: alpha(colors.danger, 0.24), paddingHorizontal: 14, paddingVertical: 12, flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
    formErrorText: { flex: 1, minWidth: 0, color: colors.danger, fontSize: 13, lineHeight: 18, fontWeight: '700' },
    modalFooter: { borderTopWidth: 1, borderTopColor: colors.shellBorder, paddingTop: 14, paddingBottom: Math.max(bottomInset, 12), backgroundColor: colors.shellBackground },
    modalActionsRow: { flexDirection: 'row', gap: 12 },
    secondaryActionButton: { minHeight: 54, minWidth: 110, borderRadius: 18, backgroundColor: colors.shellCard, borderWidth: 1, borderColor: colors.shellBorder, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 },
    secondaryActionButtonText: { color: colors.shellTextSecondary, fontSize: 14, lineHeight: 18, fontWeight: '800' },
    submitButton: { flex: 1, minHeight: 54, borderRadius: 18, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
    submitButtonText: { color: colors.onPrimary, fontSize: 14, fontWeight: '800' },
    deleteButton: { minHeight: 54, minWidth: 142, borderRadius: 18, borderWidth: 1, borderColor: alpha(colors.danger, 0.28), backgroundColor: alpha(colors.danger, 0.08), flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    deleteButtonText: { color: colors.danger, fontSize: 14, fontWeight: '800' },
    actionButtonPressed: { opacity: 0.92, transform: [{ scale: 0.99 }] },
    actionButtonDisabled: { opacity: 0.6 },
    fabContainer: { position: 'absolute' as const, bottom: Math.max(bottomInset + 90, 100), right: 18, zIndex: 100 },
    fab: { width: 60, height: 60, borderRadius: 20, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', shadowColor: colors.primary, shadowOpacity: 0.32, shadowRadius: 16, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
    fabPressed: { opacity: 0.9, transform: [{ scale: 0.95 }] },
  });

const SUMMARY_CARD_STYLES = (colors: AppColorTheme) =>
  StyleSheet.create({
    card: { borderRadius: 30, paddingHorizontal: 24, paddingVertical: 22, gap: 12, overflow: 'hidden', borderWidth: 1 },
    title: { color: colors.shellTextMuted, fontSize: 12, lineHeight: 16, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.8 },
    value: { color: colors.shellTextPrimary, fontSize: 28, lineHeight: 34, fontWeight: '900', letterSpacing: -1 },
    progressTrack: { height: 6, borderRadius: 999, backgroundColor: alpha(colors.surfaceContainerHighest, 0.44), overflow: 'hidden', marginTop: 2 },
    progressFill: { height: '100%', borderRadius: 999 },
    meta: { fontSize: 12, lineHeight: 16, fontWeight: '700' },
  });

export { DAY_SUMMARY_STYLES, ROW_STYLES, SUMMARY_CARD_STYLES };
